--practice to clean data 


--q1
--What is the average annual revenue per sector of clients that work in the sectors Insurance and Banking?


select
	CASE WHEN LOWER (sector) = 'banking' THEN 'banking'
  	WHEN LOWER (sector) = 'insurance' THEN 'insurance'
    ELSE LOWER (sector)
  END AS clin_sector
  , AVG (annual_revenue)
from meta_clients
	WHERE LOWER (sector) in ('banking', 'insurance')
GROUP BY clin_sector


--q2 
--Your manager wants to analyze the marketing spend percentage by country, but the data is not 100% clean. He mentions that you can clean the country field by using the sales team information, and shared the following mapping with you: 
--UK = United Kingdom
--FR = France
--ES = Spain
--IT = Italy
--DACH = Germany
--What is the average marketing spend percentage per country?

SELECT 
	COALESCE (country, CASE WHEN LOWER (sales_team) LIKE '%_uk_%' THEN 'United Kingdom'
  											WHEN LOWER (sales_team) LIKE '%_fr_%' THEN 'France'
    										WHEN LOWER (sales_team) LIKE '%_es_%' THEN 'Spain'
    										WHEN LOWER (sales_team) LIKE '%_it_%' THEN 'Italy'
    										WHEN LOWER (sales_team) LIKE '%_dach_%' THEN 'Germany'
    										ELSE sales_team
            					END) AS clien_country
  , AVG (marketing_spend_perc)

FROM meta_clients
GROUP BY clien_country



--q3  
-- qustion to teacher
--The data seems to be much cleaner now! Your manager is interested in comparing the revenue generated by Meta against the total marketing spend of the clients.
--What is the total marketing spend in $ (annual revenue of the client multiplied by marketing spend %) and the total revenue generated by Meta per client ID in 2022 for the cleaned up country values Spain and Italy?
--You can reuse the cleaned up country logic from question 2

SELECT mr.client_id
 	, SUM (mr.revenue) AS total_revenue
  , AVG (mc.annual_revenue*mc.marketing_spend_perc) AS marketing_spend
from meta_revenue mr 
LEFT JOIN meta_clients mc ON mr.client_id = mc.client_id
WHERE 1=1 
	AND EXTRACT (year FROM mr.dates) = 2022 
    AND COALESCE (mc.country, CASE WHEN LOWER (mc.sales_team) LIKE '%_es_%' THEN 'Spain'
    								WHEN LOWER (mc.sales_team) LIKE '%_it_%' THEN 'Italy'
    								ELSE mc.sales_team
            					END) in ('Spain', 'Italy') 
GROUP BY mr.client_id


--q4 
--Create a client list and calculate the customer penetration % for clients in 2022 with an industry that matches consumer goods.
--The customer penetration can be calculated as follows:
--Meta revenue generated in one year divided by the marketing spend $ (from question 3)
--Show the clients with the lowest customer penetration first.

SELECT mr.client_id
 	, SUM (mr.revenue) / AVG (mc.annual_revenue*mc.marketing_spend_perc) AS customer_penetrition
from meta_revenue mr 
LEFT JOIN meta_clients mc ON mr.client_id = mc.client_id
WHERE 1=1 
    AND EXTRACT (year FROM mr.dates) = 2022 
    AND (CASE WHEN lower(mc.industry) in ('consumer goods', 'consumer goods   ', 'retail & consumer goods') THEN 'retail & consumer goods'
  					ELSE lower(mc.industry)
        END) = 'retail & consumer goods'
GROUP BY mr.client_id
ORDER BY 2 ASC

--q5
--Reuse the answer of question 4.
--Clean up the industry data and calculate the customer penetration for the clients in the Retail & Consumer Goods industries based on the Meta revenue data from 2022?
--The following values should fall under Retail & Consumer Goods: retail, Retail, Consumer Goods, RCG, Retail & Consumer Goods.

SELECT mr.client_id
 	, SUM (mr.revenue) / AVG (mc.annual_revenue*mc.marketing_spend_perc) AS customer_penetrition
from meta_revenue mr 
LEFT JOIN meta_clients mc ON mr.client_id = mc.client_id
WHERE 1=1 
	AND mr.dates > '2022-01-01' 
    AND (CASE WHEN lower(mc.industry) in ('consumer goods', 'consumer goods   ',
                         'retail & consumer goods', 'retail', 'retail  ', 'rcg') 
                    THEN 'retail & consumer goods'
  			    ELSE lower(mc.industry)
        END) = 'retail & consumer goods'
GROUP BY mr.client_id


--q6
--Finally, your manager is interested in understanding how the customer penetration % of our biggest clients has changed year over year based on the changes in the revenue generated by Meta.
--We can assume that the annual revenue of the client remains consistent.
--Calculate the customer penetration % for every available year that we have Meta revenue available for for the client ID “Client_1010”

SELECT EXTRACT (year from mr.dates)
 	, SUM (mr.revenue) / AVG (mc.annual_revenue*mc.marketing_spend_perc) AS customer_penetrition
from meta_revenue mr 
LEFT JOIN meta_clients mc ON mr.client_id = mc.client_id
WHERE 1=1 
	AND mc.client_id = 'Client_1010'
GROUP BY EXTRACT (year from mr.dates)
